---
name: Test
on:
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  platform_matrix:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
       
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup wget
        run: pip install wget

      - name: Test with pytest
        run: |
          pytest